"""Exploratory data analysis (deliverable 4 of the schedule).

Produces docs/eda.md with descriptive statistics, class imbalance and the treatment of
missing values and outliers, plus the four required charts: delay distribution, default
rate by segment, seasonality and a correlation heatmap.
"""

from pathlib import Path

import matplotlib
import pandas as pd

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import seaborn as sns  # noqa: E402

from collection.config import settings  # noqa: E402
from collection.data.ingest import load_interim  # noqa: E402
from collection.features.build import build_features  # noqa: E402

sns.set_theme(style="whitegrid", palette="deep")


def _save(fig: plt.Figure, name: str) -> Path:
    destination = settings.dir_docs / "eda" / f"{name}.png"
    destination.parent.mkdir(parents=True, exist_ok=True)
    fig.tight_layout()
    fig.savefig(destination, dpi=150)
    plt.close(fig)
    return destination


def _chart_delay(invoices: pd.DataFrame) -> Path:
    fig, ax = plt.subplots(figsize=(8, 4.5))
    late = invoices.loc[invoices["days_late"] > 0, "days_late"].clip(upper=180)
    sns.histplot(late, bins=45, ax=ax)
    ax.set(
        title="Distribution of days late (late receivables)",
        xlabel="days late (capped at 180)",
        ylabel="receivables",
    )
    return _save(fig, "01-days-late-distribution")


def _chart_segment(invoices: pd.DataFrame, customers: pd.DataFrame) -> Path:
    d = invoices.merge(
        customers[["customer_id", "segment", "size_tier"]], on="customer_id", how="left"
    )
    d["defaulted"] = (d["status"] == "defaulted").astype(int)
    summary = d.groupby(["segment", "size_tier"])["defaulted"].mean().reset_index()
    fig, ax = plt.subplots(figsize=(8, 4.5))
    sns.barplot(summary, x="segment", y="defaulted", hue="size_tier", ax=ax)
    ax.set(title="Default rate by segment and customer size", ylabel="share defaulted")
    return _save(fig, "02-default-rate-by-segment")


def _chart_seasonality(invoices: pd.DataFrame) -> Path:
    d = invoices.copy()
    d["month"] = pd.to_datetime(d["due_date"]).dt.to_period("M").astype(str)
    d["was_late"] = (d["days_late"] > 0).astype(int)
    series = d.groupby("month")["was_late"].mean().reset_index()
    fig, ax = plt.subplots(figsize=(9, 4.5))
    sns.lineplot(series, x="month", y="was_late", marker="o", ax=ax)
    ax.set(
        title="Seasonality: late rate by due month",
        ylabel="share paid late",
        xlabel="due month",
    )
    ax.tick_params(axis="x", rotation=60)
    return _save(fig, "03-seasonality")


def _chart_correlation(features: pd.DataFrame, target: str) -> Path:
    numeric = features.select_dtypes("number")
    if target in numeric:
        order = numeric.corr()[target].abs().sort_values(ascending=False).head(14).index
        numeric = numeric[order]
    fig, ax = plt.subplots(figsize=(9, 7.5))
    sns.heatmap(numeric.corr(), cmap="vlag", center=0, annot=False, ax=ax)
    ax.set(title="Correlation between numeric features and the target")
    return _save(fig, "04-correlation-heatmap")


def generate_report() -> Path:
    settings.prepare_directories()
    tables = load_interim()
    invoices, customers = tables["invoices"], tables["customers"]
    features = build_features("propensity")
    target = next(c for c in features.columns if c.startswith("target_"))

    charts = [
        _chart_delay(invoices),
        _chart_segment(invoices, customers),
        _chart_seasonality(invoices),
        _chart_correlation(features, target),
    ]

    positive_rate = float(features[target].mean())
    imbalance = (1 - positive_rate) / positive_rate if positive_rate else float("inf")
    missing = (
        features.isna()
        .mean()
        .sort_values(ascending=False)
        .head(10)
        .mul(100)
        .round(2)
        .to_frame("% missing")
    )
    p99 = invoices["amount"].quantile(0.99)

    parts = [
        "# Exploratory data analysis\n",
        "> Generated by `collection eda`. Anonymized dataset in `data/interim/`.\n",
        "## Volume\n",
        pd.DataFrame(
            [{"table": n, "rows": len(df), "columns": df.shape[1]} for n, df in tables.items()]
        ).to_markdown(index=False),
        "\n## Receivable status\n",
        invoices["status"].value_counts().to_frame("receivables").to_markdown(),
        "\n## Descriptive statistics\n",
        invoices[["amount", "days_late"]].describe().round(2).to_markdown(),
        "\n## Target and class imbalance\n",
        f"- Target analysed: `{target}`\n"
        f"- Positive rate: **{positive_rate:.2%}**\n"
        f"- Negative:positive ratio: **{imbalance:.2f}:1**\n"
        f"- Eligible observations: **{len(features)}**\n",
        "\n## Missing values (top 10)\n",
        missing.to_markdown(),
        "\n## Outliers\n",
        f"- Receivables more than 180 days late: {(invoices['days_late'] > 180).sum()} "
        f"({(invoices['days_late'] > 180).mean():.2%}); capped in the charts and kept for "
        "modelling, since they are genuine write-off cases.\n"
        f"- Amounts above the 99th percentile ({p99:.2f}): "
        f"{(invoices['amount'] > p99).sum()} receivables.\n",
        "\n## Charts\n",
        *[f"![{c.stem}](eda/{c.name})\n" for c in charts],
    ]

    destination = settings.dir_docs / "eda.md"
    destination.write_text("\n".join(parts), encoding="utf-8")
    return destination
