"""Generates docs/data-dictionary.md from the domain model."""

from pathlib import Path

from collection.config import settings
from collection.data.anonymize import lgpd_report
from collection.domain.schema import (
    DEFAULT_THRESHOLD_DAYS,
    PROPENSITY_WINDOW_DAYS,
    TABLES,
    TARGET_TASK_1,
    TARGET_TASK_2,
)

HEADER = """# Data dictionary

> Generated by `collection dictionary` from `src/collection/domain/schema.py`.
> Do not edit by hand: change the schema and regenerate.

Unit of analysis of the predictive module: **the receivable (invoice)**.

| Target | Definition |
|---|---|
| `{target1}` | Already-due receivable settled within {window} days of the due date. |
| `{target2}` | Not-yet-due receivable that goes past {threshold} days late without settling. |
"""


def generate(destination: Path | None = None) -> Path:
    destination = destination or settings.dir_docs / "data-dictionary.md"
    destination.parent.mkdir(parents=True, exist_ok=True)

    parts = [
        HEADER.format(
            target1=TARGET_TASK_1,
            target2=TARGET_TASK_2,
            window=PROPENSITY_WINDOW_DAYS,
            threshold=DEFAULT_THRESHOLD_DAYS,
        )
    ]
    for table in TABLES:
        parts.append(f"\n## `{table.name}`\n\n{table.description}\n")
        parts.append(f"Primary key: `{table.key}`\n")
        parts.append("| Field | Type | Sensitivity | Description | Example |")
        parts.append("|---|---|---|---|---|")
        for f in table.fields:
            parts.append(
                f"| `{f.name}` | {f.type} | {f.sensitivity} | {f.description} | {f.example} |"
            )
        parts.append("")

    parts.append("\n## LGPD treatment per field\n")
    parts.append(lgpd_report().to_markdown(index=False))
    parts.append("")

    destination.write_text("\n".join(parts), encoding="utf-8")
    return destination
