"""Writes the model comparison report for a task."""

from pathlib import Path

import matplotlib
import pandas as pd

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import seaborn as sns  # noqa: E402
from sklearn.metrics import PrecisionRecallDisplay, RocCurveDisplay  # noqa: E402

from collection.config import settings  # noqa: E402
from collection.models.metrics import SELECTION_METRIC  # noqa: E402
from collection.models.train import TaskResult  # noqa: E402

sns.set_theme(style="whitegrid", palette="deep")


def curves(estimator, x_test, y_test, source: str, task: str) -> Path:
    fig, axes = plt.subplots(1, 2, figsize=(11, 4.5))
    RocCurveDisplay.from_estimator(estimator, x_test, y_test, ax=axes[0])
    axes[0].plot([0, 1], [0, 1], "--", color="gray", linewidth=1)
    axes[0].set_title("ROC — test split")
    PrecisionRecallDisplay.from_estimator(estimator, x_test, y_test, ax=axes[1])
    axes[1].axhline(y_test.mean(), linestyle="--", color="gray", linewidth=1)
    axes[1].set_title("Precision-recall — test split")
    destination = settings.dir_docs / "models" / source / f"{task}-curves.png"
    destination.parent.mkdir(parents=True, exist_ok=True)
    fig.tight_layout()
    fig.savefig(destination, dpi=150)
    plt.close(fig)
    return destination


def write(result: TaskResult, curve_path: Path | None = None) -> Path:
    confusion = pd.DataFrame(
        result.test.confusion,
        index=["actual negative", "actual positive"],
        columns=["predicted negative", "predicted positive"],
    )
    tuned = {c.name: c.tuned_params for c in result.candidates if c.tuned_params}

    parts = [
        f"# Predictive model — {result.task} (`{result.source}`)\n",
        "> Generated by `collection train`. Selection metric: average precision on the\n"
        "> validation split. The test split is scored once, after the champion is chosen.\n",
        _provenance_warning(result.source),
        f"- Target: `{result.target}`\n"
        f"- Champion: **{result.champion}**\n"
        f"- Decision threshold (tuned on validation): **{result.threshold:.2f}**\n"
        f"- Splits: {result.split_sizes['train']} train / "
        f"{result.split_sizes['validation']} validation / {result.split_sizes['test']} test\n",
        "\n## Model comparison\n",
        "Cross-validation uses `TimeSeriesSplit` with k=5 on the training split, so no fold\n"
        "is scored on rows that precede its own training data.\n",
        result.comparison_table().to_markdown(index=False),
        "\n## Test result (champion, scored once)\n",
        pd.DataFrame([result.test.as_row()]).round(4).to_markdown(index=False),
        "\n### Against the majority-class baseline\n",
        "A model is only useful if it beats predicting the majority class every time:\n",
        pd.DataFrame(
            [
                {
                    "model": "majority class",
                    **{k: round(v, 4) for k, v in result.test_baseline.items()},
                },
                {
                    "model": result.champion,
                    "accuracy": round(result.test.accuracy, 4),
                    "average_precision": round(result.test.average_precision, 4),
                    "roc_auc": round(result.test.roc_auc, 4),
                },
            ]
        ).to_markdown(index=False),
        "\n### Confusion matrix\n",
        confusion.to_markdown(),
        f"\nPositive rate in the test split: {result.test.positive_rate:.2%} "
        f"({result.test.n} receivables).\n",
    ]
    if tuned:
        parts.append("\n## Tuned hyperparameters\n")
        for name, params in tuned.items():
            parts.append(f"- `{name}`: {params}")
        parts.append("")
    if curve_path is not None:
        parts.append(
            f"\n## Curves\n\n![{curve_path.stem}](models/{result.source}/{curve_path.name})\n"
        )

    destination = settings.dir_docs / f"model-{result.source}-{result.task}.md"
    destination.write_text("\n".join(parts), encoding="utf-8")
    return destination


def _provenance_warning(source: str) -> str:
    """Numbers from generated data must never be read as findings."""
    if source == "synthetic":
        return (
            "> [!WARNING]\n"
            "> **These numbers are not results.** They come from the synthetic generator,\n"
            "> so they measure whether the models can recover a process that was designed\n"
            "> into the data. They verify the training protocol; they say nothing about\n"
            "> real payment behavior and must not be cited as findings.\n"
        )
    return ""


def selection_note() -> str:
    return (
        f"Champion chosen by {SELECTION_METRIC} on validation; accuracy is reported but "
        "never used to choose, because the majority class already scores high on it."
    )
